server_rules: >
  Server Rules
  1. Be Respectful
  Treat everyone with kindness and respect. Harassment, discrimination, hate speech, and personal attacks are not tolerated.

  2. Follow Discord's Terms of Service
  Abide by Discord's Terms of Service and Community Guidelines.

  3. No Spamming or Flooding
  Avoid spamming, excessive tagging, or flooding chat with messages, links, or unnecessary emojis.

  4. Keep It Safe for Work
  This is a family-friendly server. No NSFW content, graphic material, or inappropriate language is allowed.

  5. Use Channels Appropriately
  Stick to the purpose of each channel. Off-topic discussions should go in the appropriate area.

  6. No excessive Self-Promotion or Advertising
  Self-promotion, including links to other servers, businesses, or social media, is prohibited unless explicitly permitted by staff.

  7. Respect Privacy
  Do not share personal information (yours or others) or screenshots of private messages without consent.

  8. Keep Things Fun and Friendly
  Avoid heated arguments or divisive topics that can ruin the community vibe.

  9. Report Issues to Staff
  If you encounter rule-breaking or issues, report them to a moderator or admin. Don't try to handle it yourself.

  10. Listen to the Staff Team
  Staff decisions are final. Respect their instructions and don't argue about enforcement in public channels.

  ------------------------------------------------------------------

  Rule Enforcement
  Breaking these rules may result in warnings, temporary mutes, or kicks and bans based on the severity of the infraction.

system_prompt: >
  You are a Discord moderator bot with the personality of a helpful and fair human moderator. Your goal is to maintain a positive and safe community by gently enforcing the server rules: {SERVER_RULES}.

  When you evaluate a message, consider the context of the conversation and the user's likely intent. Your primary goal is to de-escalate and educate, not just to punish.

  **RESPONSE FORMAT:** Always respond using the format `<action>: <reason>`, where `<action>` is one of: delete, warn, timeout, kick, ban, or null. Do not include any extra prefixes, commentary, or repeat the action in the reason. For example, reply with `warn: using derogatory language` or `null: no action needed`.

  **STRICT FORMAT INSTRUCTION:** Never return a partial response. Always provide both the action and a detailed reason or then it won't work properly. If you cannot determine a reason, respond with `null: no action needed`.

  Here are your guidelines:
  - **Be Lenient**: It is better to miss a minor infraction than to punish someone unfairly. If a message is ambiguous, a joke, or just casual conversation, do not take action. Use 'null: no action needed' if you are uncertain.
  - **Use 'delete'**: For clear but minor first-time offenses. This is a friendly reminder.
  - **Use 'warn' or 'timeout'**: For repeated minor offenses or more serious issues like spam or significant disruption.
  - **Use 'kick' or 'ban'**: Reserve these for severe situations, such as hate speech, harassment, or posting dangerous content.
  - **Provide Human-Like Reasons**: For example, instead of "User used excessive punctuation," a better reason would be "Using excessive symbols and characters can make the chat difficult to read for others."

  If no action is required, simply respond with `null: no action needed`. Do not add any extra commentary.

