"""
Low-level Discord utility functions for Modcord.

This module provides stateless helpers for Discord-specific operations, including message deletion, DM sending, permission checks, and moderation actions. All logic here is designed for use by higher-level bot components and should not maintain state.
"""
import sys
from typing import List, Tuple, Union

import discord

from modcord.datatypes.discord_datatypes import MessageID
from modcord.util import image_utils
from modcord.util.logger import get_logger

logger = get_logger("discord_utils")

# ==========================================
# Duration/constants and choices (moved here so discord_utils is self-contained)
# ==========================================

# Human-friendly label for a permanent duration
PERMANENT_DURATION = "Till the End of Time"

DURATIONS = {
    "60 secs": 1,
    "5 mins": 5,
    "10 mins": 10,
    "30 mins": 30,
    "1 hour": 60,
    "2 hours": 120,
    "1 day": 24 * 60,
    "1 week": 7 * 24 * 60,
    PERMANENT_DURATION: sys.maxsize,
}

DURATION_CHOICES = list(DURATIONS.keys())

DELETE_MESSAGE_CHOICES = [
    discord.OptionChoice(name="Don't Delete Any", value=0),
    discord.OptionChoice(name="Previous Hour", value=60 * 60),
    discord.OptionChoice(name="Previous 6 Hours", value=6 * 60 * 60),
    discord.OptionChoice(name="Previous 12 Hours", value=12 * 60 * 60),
    discord.OptionChoice(name="Previous 24 Hours", value=24 * 60 * 60),
    discord.OptionChoice(name="Previous 3 Days", value=3 * 24 * 60 * 60),
    discord.OptionChoice(name="Previous 7 Days", value=7 * 24 * 60 * 60),
]


def bot_can_manage_messages(channel: discord.TextChannel, guild: discord.Guild) -> bool:
    """
    Determine if the bot has permission to read and manage messages in a given text channel.

    Args:
        channel (discord.TextChannel): The channel to check permissions for.
        guild (discord.Guild): The guild context to resolve the bot's member object.

    Returns:
        bool: True if the bot can read and manage messages, False otherwise.
    """
    me = guild.me

    try:
        permissions = channel.permissions_for(me)
    except Exception:
        return False

    return permissions.manage_messages and permissions.read_messages and permissions.view_channel and permissions.read_message_history and permissions.send_messages


def iter_moderatable_channels(guild: discord.Guild):
    """
    Iterate over text channels in a guild where the bot can safely manage messages.

    Args:
        guild (discord.Guild): The guild whose channels are inspected.

    Yields:
        discord.TextChannel: Channels suitable for moderation actions.
    """
    for channel in guild.text_channels:
        if bot_can_manage_messages(channel, guild):
            yield channel



def extract_embed_text_from_message(embed: discord.Embed) -> List[str]:
        """
        Extract all text content from a Discord embed.
        
        Extracts text from embed description and all fields, combining field
        names and values into formatted strings.
        
        Args:
            embed (discord.Embed): The embed to extract text from.
        
        Returns:
            List[str]: List of text strings extracted from the embed.
        """
        texts = []
        if embed.description and isinstance(embed.description, str):
            texts.append(embed.description.strip())
        texts.extend(
            f"{field.name}: {field.value}".strip() if field.name else field.value.strip()
            for field in embed.fields
            if isinstance(field.value, str) and field.value.strip()
        )
        return texts



def is_ignored_author(author: Union[discord.User, discord.Member]) -> bool:
    """
    Check if an author should be ignored by moderation handlers (e.g., bots or non-members).

    Args:
        author (discord.User | discord.Member): The user or member to check.

    Returns:
        bool: True if the author is a bot or not a member, False otherwise.
    """
    return author.bot or not isinstance(author, discord.Member)


def should_process_message(
    message: discord.Message) -> bool:
    """
    Determine if a message should be processed for moderation.
    
    Centralized filtering logic that checks:
    - Guild messages only (DMs are excluded)
    - Not from bots (including the bot itself)
    - Not from users who are not guild members
    - Has at least some text content
    - Ignores messages generated by slash commands (interactions)
    
    This function is used by both real-time message processing and history fetching
    to ensure consistent filtering rules across the application.
    
    Args:
        message (discord.Message): The Discord message to check.

    Returns:
        bool: True if the message should be processed, False otherwise.
    """
    # Ignore DMs
    if message.guild is None:
        return False
    
    # Ignore messages from bots or non-members
    if is_ignored_author(message.author):
        return False

    # Ignore messages generated by slash commands (interactions)
    # These messages have message.interaction set
    if getattr(message, "interaction_metadata", None) is not None:
        return False
    
    # Check if message has text content or image attachments
    has_text = bool((message.clean_content or "").strip())
    has_images = any(image_utils.is_image_attachment(att) for att in message.attachments)
    
    return has_text or has_images


def has_elevated_permissions(member: Union[discord.User, discord.Member]) -> bool:
    """
    Check if a member has moderator-level privileges (administrator, manage guild, or moderate members).

    Args:
        member (discord.User | discord.Member): The member to evaluate.

    Returns:
        bool: True if the member has elevated permissions, False otherwise.
    """

    if not isinstance(member, discord.Member):
        return False

    # Check computed permissions first (includes all roles)
    perms = member.guild_permissions
    if perms.administrator or perms.manage_guild or perms.moderate_members:
        return True

    # Check for elevated roles by name
    elevated_keywords = ("mod", "moderator", "admin", "staff", "owner")
    for role in member.roles:
        if role.is_default() or role.managed:
            continue
        role_name = role.name.lower()
        if any(keyword in role_name for keyword in elevated_keywords):
            return True
    
    return False



def format_duration(seconds: int) -> str:
    """
    Convert a duration in seconds to a human-readable string.

    Args:
        seconds (int): Duration in seconds.

    Returns:
        str: Human-readable duration string.
    """
    if seconds == 0:
        return PERMANENT_DURATION
    elif seconds < 60:
        return f"{seconds} secs"
    elif seconds < 3600:
        mins = seconds // 60
        return f"{mins} mins"
    elif seconds < 86400:
        hours = seconds // 3600
        return f"{hours} hour{'s' if hours != 1 else ''}"
    else:
        days = seconds // 86400
        return f"{days} day{'s' if days != 1 else ''}"




async def delete_messages_from_channel(
    channel: discord.TextChannel | discord.Thread,
    message_ids: Tuple[MessageID, ...]
) -> int:
    """Delete specific messages from a channel individually."""
    num_deleted = 0

    for msg_id in message_ids:
        try:
            msg = channel.get_partial_message(int(msg_id))
            await msg.delete()
            num_deleted += 1
        except discord.NotFound:
            continue  # message already num_deleted
        except discord.Forbidden:
            continue  # no permission
        except Exception as exc:
            print(f"Error deleting message {msg_id}: {exc}")

    return num_deleted