"""
Low-level Discord utility functions for Modcord.

This module provides stateless helpers for Discord-specific operations, including message deletion, DM sending, permission checks, and moderation actions. All logic here is designed for use by higher-level bot components and should not maintain state.
"""

import datetime
from typing import List, Tuple, Union

import discord

from modcord.datatypes.discord_datatypes import MessageID
from modcord.util import image_utils
from modcord.util.logger import get_logger

logger = get_logger("discord_utils")

# ==========================================
# Duration/constants and choices (moved here so discord_utils is self-contained)
# ==========================================

# Human-friendly label for a permanent duration
PERMANENT_DURATION = "Till the End of Time"

DURATIONS = {
    "60 secs": 1,
    "5 mins": 5,
    "10 mins": 10,
    "30 mins": 30,
    "1 hour": 60,
    "2 hours": 120,
    "1 day": 24 * 60,
    "1 week": 7 * 24 * 60,
    PERMANENT_DURATION: 0,
}

DURATION_CHOICES = list(DURATIONS.keys())

DELETE_MESSAGE_CHOICES = [
    discord.OptionChoice(name="Don't Delete Any", value=0),
    discord.OptionChoice(name="Previous Hour", value=60),
    discord.OptionChoice(name="Previous 6 Hours", value=6 * 60),
    discord.OptionChoice(name="Previous 12 Hours", value=12 * 60),
    discord.OptionChoice(name="Previous 24 Hours", value=24 * 60),
    discord.OptionChoice(name="Previous 3 Days", value=3 * 24 * 60),
    discord.OptionChoice(name="Previous 7 Days", value=7 * 24 * 60),
]


def bot_can_manage_messages(channel: discord.TextChannel, guild: discord.Guild) -> bool:
    """
    Determine if the bot has permission to read and manage messages in a given text channel.

    Args:
        channel (discord.TextChannel): The channel to check permissions for.
        guild (discord.Guild): The guild context to resolve the bot's member object.

    Returns:
        bool: True if the bot can read and manage messages, False otherwise.
    """
    me = guild.me

    try:
        permissions = channel.permissions_for(me)
    except Exception:
        return False

    return permissions.manage_messages and permissions.read_messages and permissions.view_channel and permissions.read_message_history and permissions.send_messages


def iter_moderatable_channels(guild: discord.Guild):
    """
    Iterate over text channels in a guild where the bot can safely manage messages.

    Args:
        guild (discord.Guild): The guild whose channels are inspected.

    Yields:
        discord.TextChannel: Channels suitable for moderation actions.
    """
    for channel in guild.text_channels:
        if bot_can_manage_messages(channel, guild):
            yield channel



def extract_embed_text_from_message(embed: discord.Embed) -> List[str]:
        """
        Extract all text content from a Discord embed.
        
        Extracts text from embed description and all fields, combining field
        names and values into formatted strings.
        
        Args:
            embed (discord.Embed): The embed to extract text from.
        
        Returns:
            List[str]: List of text strings extracted from the embed.
        """
        texts = []
        if embed.description and isinstance(embed.description, str):
            texts.append(embed.description.strip())
        texts.extend(
            f"{field.name}: {field.value}".strip() if field.name else field.value.strip()
            for field in embed.fields
            if isinstance(field.value, str) and field.value.strip()
        )
        return texts



def is_ignored_author(author: Union[discord.User, discord.Member]) -> bool:
    """
    Check if an author should be ignored by moderation handlers (e.g., bots or non-members).

    Args:
        author (discord.User | discord.Member): The user or member to check.

    Returns:
        bool: True if the author is a bot or not a member, False otherwise.
    """
    return author.bot or not isinstance(author, discord.Member)


def should_process_message(
    message: discord.Message) -> bool:
    """
    Determine if a message should be processed for moderation.
    
    Centralized filtering logic that checks:
    - Guild messages only (DMs are excluded)
    - Not from bots (including the bot itself)
    - Not from users who are not guild members
    - Has at least some text content
    - Ignores messages generated by slash commands (interactions)
    
    This function is used by both real-time message processing and history fetching
    to ensure consistent filtering rules across the application.
    
    Args:
        message (discord.Message): The Discord message to check.
        check_guild (bool): If True, reject messages not in a guild. Default True.
    
    Returns:
        bool: True if the message should be processed, False otherwise.
    """
    # Ignore DMs
    if message.guild is None:
        return False
    
    # Ignore messages from bots or non-members
    if is_ignored_author(message.author):
        return False

    # Ignore messages generated by slash commands (interactions)
    # These messages have message.interaction set
    if getattr(message, "interaction_metadata", None) is not None:
        return False
    
    # Check if message has text content or image attachments
    has_text = bool((message.clean_content or "").strip())
    has_images = any(image_utils.is_image_attachment(att) for att in message.attachments)
    
    return has_text or has_images


def has_elevated_permissions(member: Union[discord.User, discord.Member]) -> bool:
    """
    Check if a member has moderator-level privileges (administrator, manage guild, or moderate members).

    Args:
        member (discord.User | discord.Member): The member to evaluate.

    Returns:
        bool: True if the member has elevated permissions, False otherwise.
    """

    if not isinstance(member, discord.Member):
        return False

    # Check computed permissions first (includes all roles)
    perms = member.guild_permissions
    if perms.administrator or perms.manage_guild or perms.moderate_members:
        return True

    # Check for elevated roles by name
    elevated_keywords = ("mod", "moderator", "admin", "staff", "owner")
    for role in member.roles:
        if role.is_default() or role.managed:
            continue
        role_name = role.name.lower()
        if any(keyword in role_name for keyword in elevated_keywords):
            return True
    
    return False



def format_duration(seconds: int) -> str:
    """
    Convert a duration in seconds to a human-readable string.

    Args:
        seconds (int): Duration in seconds.

    Returns:
        str: Human-readable duration string.
    """
    if seconds == 0:
        return PERMANENT_DURATION
    elif seconds < 60:
        return f"{seconds} secs"
    elif seconds < 3600:
        mins = seconds // 60
        return f"{mins} mins"
    elif seconds < 86400:
        hours = seconds // 3600
        return f"{hours} hour{'s' if hours != 1 else ''}"
    else:
        days = seconds // 86400
        return f"{days} day{'s' if days != 1 else ''}"


def parse_duration_to_minutes(human_readable_duration: str) -> int:
    """
    Convert a human-readable duration label to its value in minutes.

    Args:
        human_readable_duration (str): Duration label from DURATION_CHOICES.

    Returns:
        int: Duration in minutes, or 0 if not found.
    """
    return DURATIONS.get(human_readable_duration, 0)


async def delete_recent_messages(guild, member, seconds) -> int:
    """
    Delete recent messages from a member across all moderatable channels within a time window.

    Args:
        guild (discord.Guild): The guild to search for messages.
        member (discord.Member): The member whose messages are deleted.
        seconds (int): Time window in seconds to look back.

    Returns:
        int: Number of messages deleted.
    """
    if seconds <= 0:
        raise ValueError("Seconds must be greater than 0 for message deletion.")

    window_start = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(seconds=seconds)
    deleted_count = 0

    for channel in iter_moderatable_channels(guild):
        try:
            async for message in channel.history(after=window_start):
                if message.author.id == member.id:
                    await delete_message(message)
                    deleted_count += 1

        except Exception as exc:
            logger.warning(f"Error deleting messages in {channel}: {exc}")

    return deleted_count



async def delete_message(message: discord.Message) -> bool:
    """
    Attempt to delete a Discord message, suppressing recoverable errors.

    Args:
        message (discord.Message): The message to delete.

    Returns:
        bool: True if deletion succeeded, False otherwise.
    """
    # Safety check to prevent DM message deletion which would raise an error
    if isinstance(message.channel, Union[discord.DMChannel, discord.PartialMessageable]):
        logger.error(f"Cannot delete message in DM channel: {message.id}")
        assert False, "Attempted to delete a message in a DM channel, which is ILLEGAL."
    
    try:
        await message.delete()
        return True
    
    except discord.NotFound:
        logger.warning(f"Message ID {message.id} not found in channel: {message.channel.name}")
    except discord.Forbidden:
        logger.warning(f"No permission to delete message {message.id}")
    except Exception as exc:
        logger.error(f"Error deleting message {message.id}: {exc}")

    return False



async def delete_messages_from_channel(
    channel: discord.TextChannel,
    message_ids: Tuple[MessageID, ...],
) -> int:
    """Delete specific messages from a single channel.

    Uses Discord's bulk-delete endpoint for messages younger than 14 days,
    falling back to individual deletion for older messages.

    Args:
        channel: The text channel containing the messages.
        message_ids: Message IDs to delete.

    Returns:
        Number of messages successfully deleted.
    """
    if not message_ids:
        return 0

    now = discord.utils.utcnow()
    bulk_cutoff = now - datetime.timedelta(days=14, minutes=-5)  # small buffer

    bulk_eligible: list[discord.Object] = []
    old_ids: list[int] = []

    for mid in message_ids:
        int_id = int(mid)
        # Snowflake → creation time (Discord epoch: 2015-01-01)
        created_at = datetime.datetime.fromtimestamp(
            ((int_id >> 22) + 1420070400000) / 1000,
            tz=datetime.timezone.utc,
        )
        if created_at >= bulk_cutoff:
            bulk_eligible.append(discord.Object(id=int_id))
        else:
            old_ids.append(int_id)

    deleted = 0

    # Bulk delete (batches of 100, Discord limit)
    for i in range(0, len(bulk_eligible), 100):
        batch = bulk_eligible[i : i + 100]
        try:
            await channel.delete_messages(batch)
            deleted += len(batch)
        except discord.NotFound:
            # Some messages already gone — fall back to individual
            for obj in batch:
                try:
                    msg = channel.get_partial_message(obj.id)
                    await msg.delete()
                    deleted += 1
                except (discord.NotFound, discord.Forbidden):
                    pass
                except Exception as exc:
                    logger.error("Error deleting message %s individually: %s", obj.id, exc)
        except discord.Forbidden:
            logger.warning("Missing permissions to bulk-delete in #%s", channel.name)
        except Exception as exc:
            logger.error("Bulk delete error in #%s: %s", channel.name, exc)

    # Individual delete for old messages
    for msg_id in old_ids:
        try:
            msg = channel.get_partial_message(msg_id)
            await msg.delete()
            deleted += 1
        except discord.NotFound:
            logger.debug("Old message %s not found in #%s", msg_id, channel.name)
        except discord.Forbidden:
            logger.warning("No permission to delete message %s in #%s", msg_id, channel.name)
        except Exception as exc:
            logger.error("Error deleting old message %s: %s", msg_id, exc)

    logger.debug(
        "[DELETE] Deleted %d/%d messages in #%s",
        deleted,
        len(message_ids),
        channel.name,
    )
    return deleted



def has_permissions(application_context: discord.ApplicationContext, **required_permissions) -> bool:
    """
    Check if the console issuer has all specified permissions in the guild.

    Args:
        application_context (discord.ApplicationContext): The console context.
        **required_permissions: Permission flags to check.

    Returns:
        bool: True if all permissions are present, False otherwise.
    """
    if not isinstance(application_context.author, discord.Member):
        return False
    return all(getattr(application_context.author.guild_permissions, permission_name, False) for permission_name in required_permissions)